set dotenv-load

VERSION := "0.1.0"
YEAR := `date +%Y`
LANGUAGES := "spa_Latn swh_Latn"

MSI_PATH := "./src-tauri/target/release/bundle/msi/Ascribe_" + VERSION + "_x64_en-US.msi"
MSIX_PATH := "./packaging/ascribe-" + VERSION + ".msix"
PACKAGE_NAME := "FishArmy100.Ascribe"
PACKAGE_DISPLAY_NAME := "Ascribe"
PUBLISHER_NAME := "{{$PUBLISHER}}"
PUBLISHER_DISPLAY_NAME := "FishArmy100"

gen-config:
    #!/usr/bin/env bash
    cat > "./packaging/ConversionTemplate.xml" << EOF
    <?xml version="1.0" encoding="utf-8"?>
    <MsixPackagingToolTemplate
        xmlns="http://schemas.microsoft.com/appx/msixpackagingtool/template/2018">

        <Settings
            EnforceMicrosoftStoreVersioningRequirements="true" />

        <SaveLocation
            PackagePath="{{MSIX_PATH}}" />

        <Installer
            Path="{{MSI_PATH}}" />

        <PackageInformation
            PackageName="{{PACKAGE_NAME}}"
            PackageDisplayName="{{PACKAGE_DISPLAY_NAME}}"
            PublisherName="CN={{PUBLISHER_NAME}}"
            PublisherDisplayName="{{PUBLISHER_DISPLAY_NAME}}"
            Version="{{VERSION}}.0" />

    </MsixPackagingToolTemplate>
    EOF

update-version:
    sed 's/"version": "[^"]*"/"version": "{{VERSION}}"/' ./package.json > ./package.json.temp
    mv ./package.json.temp ./package.json

    sed 's/^version = ".*"$/version = "{{VERSION}}"/' ./src-tauri/cargo.toml > ./src-tauri/cargo.toml.temp
    mv ./src-tauri/cargo.toml.temp ./src-tauri/cargo.toml 

gen-rust-meta:
    #!/usr/bin/env bash
    cat > "./src-tauri/src/meta.rs" << EOF

    // -------- DO NOT MODIFY: Generated by justfile --------

    pub const APP_VERSION: &'static str = "{{VERSION}}";
    pub const APP_YEAR: u32 = {{YEAR}}; 
    EOF

gen-ts-meta:
    #!/usr/bin/env bash
    cat > "./src/meta.ts" << EOF

    // -------- DO NOT MODIFY: Generated by justfile --------

    export const APP_VERSION: string = "{{VERSION}}";
    export const APP_YEAR: number = {{YEAR}};
    EOF


gen-meta: gen-rust-meta gen-ts-meta
    

npm-install:
    npm install

translate:
    npx auto-i18n-cli                                       \
        -i "./src"                                          \
        -o "./src/assets/translations/translations.json"    \
        -s eng_Latn                                         \
        -l {{LANGUAGES}}                                    \
        -b azure                                            \
        --azureKey $AZURE_KEY

build: npm-install update-version gen-meta translate 
    npm run tauri build

msix: build gen-config
    powershell.exe -NoProfile -Command "MsixPackagingTool.exe create-package --template packaging/ConversionTemplate.xml -v"

full-build: msix 
