name = "ASV"
description = """

<h1>American Standard Version (ASV)</h1>
<p>
    <em>Sometimes called the Revised Version, American Edition</em>
</p>

<h2>Overview</h2>
<p>
    The <strong>American Standard Version (ASV)</strong> is an English translation of the Christian Bible,
    first published in <strong>1901</strong>. It was developed as the American counterpart to the
    <strong>English Revised Version (ERV)</strong> of 1885. The ASV reflects the work of American scholars
    who collaborated with the British revisers but later issued their own edition. It is valued for its
    accuracy and relatively literal translation style.
</p>

<h2>Textual Basis & History</h2>
<ul>
    <li><strong>Old Testament:</strong> Based on the Hebrew <em>Masoretic Text</em>, similar to the ERV.</li>
    <li><strong>New Testament:</strong> Based on the Greek <em>Textus Receptus</em> with reference to
        critical Greek texts available in the late 19th century.</li>
    <li><strong>Origins:</strong> Grew out of the <em>Revised Version (1881–1885)</em>, with
        distinctive American renderings and revisions.</li>
    <li><strong>Subsequent Influence:</strong> Served as the foundation for later translations,
        including the <em>Revised Standard Version (RSV)</em> and the <em>New American Standard Bible (NASB)</em>.</li>
</ul>

<h2>Structure</h2>
<p>
    Like most Protestant Bibles, the ASV contains the <strong>66-book canon</strong>:
    <strong>39</strong> Old Testament books and <strong>27</strong> New Testament books.
    Unlike the KJV’s original 1611 edition, the ASV generally does not include the <em>Apocrypha</em>.
</p>

<h2>Language & Style</h2>
<ul>
    <li><strong>Register:</strong> Late 19th-century English, more literal and less ornate than the KJV.</li>
    <li><strong>Pronouns:</strong> Retains traditional forms such as <em>thee, thou, thy</em> in prayer
        and in reference to God.</li>
    <li><strong>Divine Name:</strong> Frequently uses <em>“Jehovah”</em> to render the Tetragrammaton
        (YHWH) in the Old Testament.</li>
    <li><strong>Features:</strong> Includes chapter and verse divisions, with marginal notes and
        alternative readings.</li>
</ul>

<h2>Impact & Use</h2>
<p>
    The ASV became influential among scholars and churches seeking a more literal translation than the KJV.
    Although less widely read by the general public, it shaped subsequent English Bible versions in the 20th century
    and is still appreciated by some readers for study and historical interest.
</p>

<h2>Common Editions</h2>
<ul>
    <li><strong>1901 First Edition:</strong> The original American Standard Version release.</li>
    <li><strong>Later Reprints:</strong> Various publishers have kept the ASV in print or digital form,
        often emphasizing its historical and textual significance.</li>
</ul>

<h2>Notes</h2>
<ul>
    <li><strong>Public Domain:</strong> The ASV text (1901) is in the public domain worldwide.</li>
    <li><strong>Study Helps:</strong> Modern editions may add introductions, notes, and cross-references,
        which can be separately copyrighted.</li>
</ul>


"""
language = "en"
data_source = "https://github.com/scrollmapper/bible_databases/tree/master/sources/en/KJV"

[books]
Gen = "Genesis"  
Exod = "Exodus"  
Lev = "Leviticus"  
Num = "Numbers"  
Deut = "Deuteronomy"  
Josh = "Joshua"  
Judg = "Judges"  
Ruth = "Ruth"  
1Sam = "1 Samuel"  
2Sam = "2 Samuel"  
1Kgs = "1 Kings"  
2Kgs = "2 Kings"  
1Chr = "1 Chronicles"  
2Chr = "2 Chronicles"  
Ezra = "Ezra"  
Neh = "Nehemiah"  
Esth = "Esther"  
Job = "Job"  
Ps = "Psalms"  
Prov = "Proverbs"  
Eccl = "Ecclesiastes"  
Song = "Song of Solomon"  
Isa = "Isaiah"  
Jer = "Jeremiah"  
Lam = "Lamentations"  
Ezek = "Ezekiel"  
Dan = "Daniel"  
Hos = "Hosea"  
Joel = "Joel"  
Amos = "Amos"  
Obad = "Obadiah"  
Jonah = "Jonah"  
Mic = "Micah"  
Nah = "Nahum"  
Hab = "Habakkuk"  
Zeph = "Zephaniah"  
Hag = "Haggai"  
Zech = "Zechariah"  
Mal = "Malachi"  
Matt = "Matthew"  
Mark = "Mark"  
Luke = "Luke"  
John = "John"  
Acts = "Acts"  
Rom = "Romans"  
1Cor = "1 Corinthians"  
2Cor = "2 Corinthians"  
Gal = "Galatians"  
Eph = "Ephesians"  
Phil = "Philippians"  
Col = "Colossians"  
1Thess = "1 Thessalonians"  
2Thess = "2 Thessalonians"  
1Tim = "1 Timothy"  
2Tim = "2 Timothy"  
Titus = "Titus"  
Phlm = "Philemon"  
Heb = "Hebrews"  
Jas = "James"  
1Pet = "1 Peter"  
2Pet = "2 Peter"  
1John = "1 John"  
2John = "2 John"  
3John = "3 John"  
Jude = "Jude"  
Rev = "Revelation"
